name: Deploy to Elastic Beanstalk

on:
  workflow_run:
    workflows: ["Deploy to ECR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_NAME: cc-ai-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        env:
          EB_ENVIRONMENT: e-fxufhrwujm
          ECR_IMAGE_URI: ${{ secrets.ECR_URI }}:latest 
        run: |
          aws elasticbeanstalk update-environment --environment-name $EB_ENVIRONMENT --version-label $GITHUB_SHA --option-settings Namespace=aws:elasticbeanstalk:container:docker,OptionName=Image,Value=$ECR_IMAGE_URI
