name: Deploy to Elastic Beanstalk

on:
  workflow_run:
    workflows: ["Deploy to ECR"]
    types:
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ECR_NAME: cc-ai-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 980921737519.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build and push Docker image to ECR
        run: |
          docker build -t $ECR_NAME .
          docker tag $ECR_NAME:latest ${{ secrets.ECR_URI }}:latest
          docker push ${{ secrets.ECR_URI }}:latest

      - name: Deploy to Elastic Beanstalk
        env:
          EB_ENVIRONMENT: e-fxufhrwujm
        run: |
          aws elasticbeanstalk update-environment --environment-name $EB_ENVIRONMENT --version-label $GITHUB_SHA --option-settings Namespace=aws:elasticbeanstalk:container:docker,OptionName=Image,Value=${{ secrets.ECR_URI }}:latest
